FROM --platform=linux/amd64 ubuntu:18.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y vim less file locate && echo 'alias locate="updatedb && locate"' >> ~/.bashrc

COPY . /repo
WORKDIR /repo/trunk
RUN make -j8
